### ISSUE TITLE
MV* prototype

### ISSUE THREAD

**Issue by gregpabian** [ckeditor/ckeditor5-design#10]
On branch [mvc-samples](https://github.com/ckeditor/v5-protos/tree/mvc-samples) I added some usage examples of the MV\* framework prototype I've been working on recently. This is an "umbrella" issue to discuss them and the whole idea.

**Comment by fredck** [comment]
I've enlarged the docs to describe what we should expect to have in the model's state:
https://github.com/ckeditor/ckeditor5-design/wiki/MVC#the-models-state

**Comment by Reinmar** [comment]
The implementation on MV* was refactored a couple of times but we finally came to a point where we're comfortable with the result. It can be now found in https://github.com/ckeditor/ckeditor5-ui.
