### ISSUE TITLE
Stop using tristate for commands

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#111]
In the CKEditor  we have tristate commands. They can be "on", "off" or "disabled". And we have a lot of problems with switching back from the "disabled" mode. It is hard to decide if the command should be "on" or "off". Some time ago I had an idea how to solve it: http://dev.ckeditor.com/ticket/12929

But recently I realised that the whole concept is wrong. There is nothing like tristate. The command can be "on" or "off". Beside that it could be "enabled" or "disabled". It is not a tristate - these are two, two state properties.

When you put the caret into the bolded text, the bold command is "on". When you put it in the unbolded text, the command is "off". That is it.

When you can not apply the command, it is "disabled", when you can, it is "enabled". It may be "disabled" because editor is in the read-only mode, because of the context, because of any other reason. Note that "disable" command can still be "on" or "off". When you put the caret into the bolded text, the bold command is "on", even if it is disabled (so you can not switch it to "off").

You can even have a button which is "disabled" and "on":

![image](https://cloud.githubusercontent.com/assets/1166967/12640853/93e205d0-c5ac-11e5-893c-6263efa5ab70.png)
(source: google material design)

And one more thing. Some feature, like typing, enter key, can be "enabled" or "disabled", but can not be "on" or "off".

**Comment by Reinmar** [comment]
Definitely +1.

**Comment by fredck** [comment]
Actually it is just a matter of finding the right words to justify any decision, as you did :P

**"Tri-state" makes a lot of sense**. Just read "disabled" as "not applicable" to understand it right. It's like a glass that may have water... if the water hot or cold if there is no water? 

Clarifying this doesn't mean that we need to have it though. The change sounds good for me as well.

**Comment by Reinmar** [comment]
Let's move any further discussion to #124 as it redefines the commands concept.
