### ISSUE TITLE
Types and variables naming

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-design#12]
# Overview

We should conclude the way that we want to name types / variables.

## Common rules

There is no doubt that we want to use camelCase, that's cool. There are few details that needs to be discussed:

### Acronyms

How to use acronyms? Do we use them like a word, or all uppercased?

Just off the top of my head, I can name one monster: `XMLHttpRequest`.

CKE4: Generally we're doing really good job treating acronyms as a words, I had really to look deep down to find some examples of violating such rule.

So we commonly have members like: `getHtml`, `getInnerXml`, `addContentsCss`.

Violating members are: `onCDATA`, `fromBBCode`.

I think that we should treat all acronyms (no matter what) as a word.

## Variables

Camelcase, starting with lowercase, eg. `addItem`, `requestType`, `getCount`, `select`.

## Types

The same rules applies as to Variables, with the exception that they're uppercased, so:

`Editor`, `ContentFilter`, `FocusManager`, `MenuButton`, `Command`, `XmlParser`

## Namespaces

How do we want to tread namespaces? Do we want to name them as variables, or like types?

Naming it as variables would make sense, so it would make chains like:

`dom.Element`, `ui.button.Handler`, `ui.dialog.JumpingDialog`

## How do we name main CKEDITOR global variable?

I believe  for compatibility sake we should stick to capitalized? So `CKEDITOR` remains.

I ask politely for making a conclusion as I want to apply our new standard to the AC right away.

**Comment by fredck** [comment]
As for for what has been discussed so far, I'm closing this one.
