### ISSUE TITLE
Names for editor's main view controllers

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#123]
Editor's main view controller is the one which defines and bootstraps its main elements and regions. For example in the classic editor in CKEditor 4 there's the "chrome" structure (so the main div and top, editable and bottom spaces). In CKEditor 5 this structure will be (or at least it looks like this in the current prototype) extended with a definition of the "floating" space, so a space for dialogs, floating panels, etc.). The goal is that destroying this controller should destroy the whole editor UI.

I’m now trying to find a good name for that main controller. For the classic editor that could be a “Container” or a “BoxContainer”, but then I can’t find a name for a typical editor with a floating toolbar (and e.g. an inline editable). Such an editor doesn’t create any “box” or “container” or whatever because its toolbar and other components are floating. I can’t name it “FloatingContainer” because the container doesn’t exist, so it definitely does not float :D. Moreover, the classic container can also have floating parts, so floatiness isn’t the important factor here.

I’m thinking now about `BoxContainer` (for classic-like editors) and `VirtualContainer` (for inline-like editors). They would inherit from `BaseContainer` (defining the common regions such as the floating one).

**Comment by oleq** [comment]
`RootController`?

**Comment by Reinmar** [comment]
Root controller of what? Besides – I still need a name for at least two types of these controllers – for the one in the classic editor case and the one in the inline editor case.

**Comment by fredck** [comment]
Couldn't the `EditorController` defaults to inline like editors having `BoxEditorController` inheriting from it?

**Comment by Reinmar** [comment]
Hm... Good question. We could try to start like this, because theoretically (so far) the boxed editor extends the features of the "box-less" UI by registering the main element (the box) template and regions inside it. But we'd need to carefully extend the base class, so the extensions are also valid for the boxed editor class and other possible subclasses. This would be tricky...

For instance, we already have "editables" collection in the box-less editor. This collection (and assigned to it virtual region) keeps the elements which weren't created by the editor (because editor reuse existing elements). However, this region will not make much sense in the boxed editor. It would work (because it does nothing – at least for now) but it would be confusing.

I predict more issues like this and the reason for them would be that the boxed editor **is not** the box-less editor. So we need one base class and two variants of it. If anyone wants a hybrid solution, he/she can create another subclass.

While discussing this we realised one more thing – so far in the prototype I had the `UI` class being a generic UI loader (handling skins, some configuration, languages, initialization, etc.). At the same time I had `Chrome` controlling the... actually what? It implementation was empty – it was defining only regions and bootstraping its view (the view held the other part, so the definition of the editor box if it had one). Therefore, I propose to merge those classes for now. If we'll identify a lot more responsibilities, we can split those to separate classes, but all will be centralized in the UI class.

So the final proposal is:

* EditorUI
  * BoxlessEditorUI
  * BoxedEditorUI

And that's it :)
