### ISSUE TITLE
Features: Features concept

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-design#129]
_This is the aggregate issue for all subjects related to features. I broke it into multiple issues because it was too huge wall of text._
# Features Concept

Features are plugins which bring Tree Model manipulation and Tree Model / Tree View conversion utilities to the editor with corresponding UI. Features glue together data, view and UI and are driving force behind changes visible for the user when creating content. Features are loaded by the editor using configuration option.

From technical point of view, `Feature` class will extend `Plugin` class, so anything that is true for `Plugin` also applies to `Feature`. `Feature` main role is to set up and publish `Command`s, converters and UI. A `Feature` should have only a single instance in the editor. As any other `Plugin`, `Feature` may require other `Plugin`s or files to work.
### Commands
#124
### Converters
#125
### Schema
#126
### UI
#127
### Feature example: Bold
#128

**Comment by scofalik** [comment]
I've pushed `t/features` branch: https://github.com/ckeditor/ckeditor5-core/tree/t/features

Since we are getting close to having PR with feature related scripts, this time I am writing here to have the summary in one place. If you are willing to discuss particular part of code, let's move to related issue.

Summary:
* I've added some integration stuff in `core.Editor`. Take a look there, I've added some members into it.
* Commands concept is almost closed. I guess we agree on anything. This part is probably PR-ready, though there are two things I don't like:
 * `Command.checkSchema` - function maybe could be renamed to something more generic. It's implementation is completely feature-dependend anyway. Maybe it could be called `checkDefault` or `checkEnabled`. Then, features not related to Tree Model might use it for different checks without having to define another function or use function with unrelated name.
 * `Command.execute` - command should not be executed if it is disabled. Where to put that logic? It should probably be in `execute()` but this means that every feature has to put that `if` in it's `execute()` implementation (see https://github.com/ckeditor/ckeditor5-core/blob/t/features/src/command/attributecommand.js#L113).
* Converters are stricly related to feature classes. The common converters will be written as helpers/function factories so it will be easy to define and use them. But this is not the part of this issue. I am still waiting for final API of `core.treeView.TreeView` / `core.treeView.Writer` (?). `core.Feature` and `BoldFeature` class are *WIP* and won't be included in upcoming PR. `BoldFeature` will be moved to it's own package when it's done.
* `core.treeModel.Schema` is at the point where it is usable and is enough for our small needs (bold feature, `AttributeCommand`) but is not perfect and will be worked on. Still, I think it is PR-ready at this point, it will just be heavily enhanced in future, basing on our needs (right now I am sure we have to add possibility to register items to schema with custom callbacks checking whether they are valid, also we use strings everywhere internally - maybe code structure would be better if actual objects are used).
* UI - nothing done here right now, though this is the most separated part of the issue and can be added later one. We can easily test how features work without UI.
* Everything *should be* documented and tested with 100% code and branch coverage.

I think I might make a PR with schema and commands and some related stuff (from top of my head - in `core.Editor` and modified `EmitterMixin.fire`) if we agree that the code is ready.

**Comment by Reinmar** [comment]
1. Commands:
  * As @pjasiun proposed we could change `Command.checkEnabled()` to `Command.refresh()`. I'm all for that.
  * `Command.checkEnabled()` makes sense
  * As for `Command.execute()` in CKEditor 4 we had it a bit differently what wasn't creating this issue. You were passing the `exec()` function as a property of command definition. The `Command.exec()` then does the check and executes the right method of the command definition. We could do it this way in CKE 5 as well. The specific command would define e.g. a private/protected `_execute()` method and the `execute()` method would come from the base class and contain all the logic.

**Comment by Reinmar** [comment]
> Converters are stricly related to feature classes. The common converters will be written as helpers/function factories so it will be easy to define and use them.

What do you mean?

> Still, I think it is PR-ready at this point, it will just be heavily enhanced in future,

I definitely agree. It's too exhausting now to try to imagine all the possible scenarios. Let's work on this over time.

> UI - nothing done here right now, though this is the most separated part of the issue and can be added later one. We can easily test how features work without UI.

The bases of the UI lib just landed on master branches. See ckeditor/ckeditor5-core#209 for more info.

> I think I might make a PR with schema and commands and some related stuff (from top of my head - in core.Editor and modified EmitterMixin.fire) if we agree that the code is ready.

I wouldn't touch EmitterMixin.fire now as it's a part of a bigger task on which I wouldn't like to work for now (https://github.com/ckeditor/ckeditor5-core/issues/200#issuecomment-185125855). So, right now you can workaround this with fire not returning anything (just pass the value by reference using an object).

**Comment by scofalik** [comment]
1. The "old" `Command.checkEnabled()` already got changed to `Command.refreshState()`.
2. I also wondered whether it would be good to to introduce something like `_execute()`:
In `Command.js`:
```javascript
execute() {
  if ( this.isEnabled ) {
    this._execute();
  }
}
```
In specific command:
```javascript
_execute() {
  // command specific logic here
}
```

But I don't like that these methods have so similar names. Any propositions?

**Comment by scofalik** [comment]
> > Converters are stricly related to feature classes. The common converters will be written as helpers/function factories so it will be easy to define and use them.
> 
> What do you mean?

I meant that converters will be used only in feature classes, not commands, so it is fine to push commands code to the master and wait for converters to push features code.

**Comment by Reinmar** [comment]
I thought about `_action()`, but it's an invalid name for a method. That should be a property then – very bad idea.

BTW. using different names won't help as the developer may not grasp the connotation that `execute()` triggers some other method. I mean... that would be confusing as well :D.

**Comment by pjasiun** [comment]
> Commands:
> As @pjasiun proposed we could change Command.checkEnabled() to Command.refresh(). I'm all for that.
> Command.checkEnabled() makes sense

:+1: 

> As for Command.execute() in CKEditor 4 we had it a bit differently what wasn't creating this issue. You were passing the exec() function as a property of command definition. The Command.exec() then does the check and executes the right method of the command definition. We could do it this way in CKE 5 as well. The specific command would define e.g. a private/protected _execute() method and the execute() method would come from the base class and contain all the logic.

As Szymon mentioned in the previous post, there methods with similar names are strange. And, 
despite it was my first thought too, I think that it is much simpler for user who check the example code that: "There is a check `if ( !this.isEnabled() ) { return; }` at the begging of the `execute()`, because if it is not enabled it should not be executed. I need to do the same."
Then:
"I see two method: `_action` and `execute`. One I define, another one I call. Why I can not define the first one, or call the second one? What is happening in the middle?"
I do not believe users read docs. They take a code and modify it.

But it is just a thought. I understand the profit of the propose solution and agree that it is not that complex to understand. Then I think that `execute` and `_execute` (or `doExecute`) is simpler.

**Comment by fredck** [comment]
> (or doExecute)

+1

**Comment by Reinmar** [comment]
Similarly to #124 – done, working, will be documented soon.
