### ISSUE TITLE
Utils lib

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#13]
Do we want to base our utils lib on the Lo-Dash or underscore?

Lo-Dash is 28kb (minified not gzipped) and we definitely don't need all of it. We could [build](https://lodash.com/custom-builds) a custom version, though. I would integrate it with our tools by copying methods we want to our object, so we will be able to extend it without modifying the original object. This way we'll be able to use the same Lo-Dash library which the website uses.

**Comment by fredck** [comment]
Closed with https://github.com/ckeditor/ckeditor5-core/issues/7
