### ISSUE TITLE
Naming convention for classes and files in UI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#130]
Usually it's most logical to name the file like the class – e.g. `plugincollection.js` implements `PluginCollection` class.

However, when we have a typical component which consists of a controller and view (and perhaps a model as well), then we keep them in a directory called like the component. It could be tempting to do this:

```
components/button/
    controller.js (or button.js)       // Implements the Button class
    view.js                            // Implements the ButtonView class
    model.js                           // Implements the ButtonModel class
```

However, then, when you work on multiple components at the same time you have multiple "view" or "model" files loaded in your text editor what's super confusing. Similar (but actually worse, because these files now greatly resemble themselves) to what we had with "plugin.js" in CKEditor 4.

Therefore I'm considering the following convention:

```
components/button/
    button.js               // Implements the Button class
    buttonview.js           // Implements the ButtonView class
    buttonmodel.js          // Implements the ButtonModel class
```

It will create super long paths (e.g. I have `boxededitorui/boxededitoruiview.js`) but should reduce the confusion.

WDYT?

**Comment by fredck** [comment]
+1 for full names.
