### ISSUE TITLE
Starting component prototypes in ckeditor5-core

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#131]
I want to propose a workflow in which before some implementation stabilises to a certain level it's kept in ckeditor5-core.

That level of stabilisation may depend on the code in question. For instance, it may be the moment when it makes sense to write tests for such a code, or when we're sure that the whole package will really exist (that we won't merge it or remove it in a couple of days and that its name is good).

The code can either be kept as test asset (then it doesn't need tests and can be even merged to master) or in `src/` but then such code cannot reach the master.

The goal of this workflow is to save us some additional work and hence time. E.g. I've been creating repositories for editables and creators but the names and code were changing constantly so I had delete the repos and I couldn't write tests. Also, all the pieces were highly related and were changing at the same time. Finally, I decided that those pieces of the whole puzzle which will eventually land in `ckeditor5-core` anyway will land there now, but all the rest are just test assets.

**Comment by fredck** [comment]
Please note that you're most likely to lose the git history for such code once you move it to it's own repo, which is a pretty bad.

**Comment by pjasiun** [comment]
Use filter branch, Luke! https://git-scm.com/docs/git-filter-branch

**Comment by pjasiun** [comment]
But I agree that it is painful sometimes.

**Comment by Reinmar** [comment]
I'm talking here about prototypes. Prototypes are not the final code and hence are likely to be coded differently anyway. You don't need the history then.

As soon as a prototype reaches the point when you start thinking about it as about a real code, then you need tests and removing the prototypal garbage. At this point you start caring more about the little details which are nice to be preserved in the history.

And one more thing – prototypes must be easy to create and discard. Otherwise you start trying to write the final code from the beginning which is the thing that often slows you down.

**Comment by Reinmar** [comment]
This didn't seem to be an issue during the past year, so I'm closing this. And we have https://github.com/ckeditor/ckeditor5-labs
