### ISSUE TITLE
Contest: Name for the editing + data model + output layer

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#138]
We are trying to find a name for one of the two main building blocks.

One of them is **UI** which covers the editor UI such as toolbars, buttons, dialogs and all things that glue and implement those (so UI controllers, views, etc.). This layer should more or less be seen as a pretty generic and replaceable implementation of the editor UI.

The second building block covers all what happens around data and editing. This layer contains things such as:

* the tree data model – the abstract syntax tree of the editor data plus the whole OT stuff (so the data manipulation logic),
* the editable view – rendering from the tree data model to the editable and handling the opposite direction which is interaction with the user (reaction to selection changes, key presses, mutations, etc.),
* the data view – rendering from the tree data model to editor output data (`editor.getData()`) and the opposite direction (`editor.setData()`).

We need to find a good name for the second building block. This name will be used as:

* the namespace grouping all the things I listed above (which are located in the core),
* but also inside features, because features will also be split into their XXX part and the UI.

So far we were considering the following:

* **data** – I like it, because it's short and it sounds familiar and it UI+data sounds great, but there's a clash with the "editor data" meaning the output,
* **content** – PJ likes it, me not because it's data's synonym and using a data's synonym to cover data, data model and other things doesn't seem right; beside, it's not that concise,
* ?

Do you have any other ideas? Maybe some longer name with a nice acronym as ACF? This name will be used all around our code base and by all features, so it must be very good. Short and precise. And it would be best if it was unique, so we don't have any clash with the existing names.

**Comment by Reinmar** [comment]
So far, personally I'm for "data". I don't see the clash with the editor's data as that problematic and "data" is perfect in all other terms.

However, if anyone will find a better name, I'll be ok with changing my preference.

**Comment by scofalik** [comment]
This is not really data so any synonym is not doing it. Words that come to my mind are: editor, base, framework, logic. But they do not fit well as names for namespace or parts of package names.

**Comment by scofalik** [comment]
BTW. we are already using name `core`, is there any problem sticking with it? Right now UI is a part of core but maybe it could be decoupled and then core will be core. I think it fits great.

**Comment by Reinmar** [comment]
The important thing to remember is that most features will need to be split to the same two layers – the UI and the XXX. We can't say "BoldEditor" or "BoldFramework". "BoldBase" sounds well, but "base" is so meaningless...

Therefore, I really like the idea to find a unique name which would make for a good acronym.

**Comment by scofalik** [comment]
And if we are really going to use parts of what we create in CKE5 in our other projects, maybe these namespaces actually have some sense:
`ck.ui.xxxx`
`ck.editor.xxxx`

In future, i.e.: `ck.finder.xxxx`

**Comment by pjasiun** [comment]
It not about liking "data" or "content". It is about the naming collision. One of the part of this block will be data handling (data view), which will contain data processor, data view class, converters for data.

But then, we have the second part, editable view, and also a model. If the whole will be called "data", it will be really hard to talk about this: "Data has 2 views: editable view and data view. It means that editable view is a view and is in a data namespace, but please do not confuse it with a data view. Also note that data view is not the only view in the data." Even talking for us would be hard, if we will not use uniq names, and talking with the community, people who do not know much about architecture would be painful.
 
Also note that this block will cover thinks like DOM mutation or selection observer or rendering. Data sounds like a model, not like a DOM manipulation.

But the second argument is less important, in my opinion. We will define what this word means, and it will be meaningless for everybody who do not read docs, anyway. The most important is to use different names for different concepts.

**Comment by pjasiun** [comment]
> Therefore, I really like the idea to find a unique name which would make for a good acronym.

:+1:

**Comment by pjasiun** [comment]
> BTW. we are already using name core, is there any problem sticking with it? Right now UI is a part of core but maybe it could be decoupled and then core will be core. I think it fits great.

Also sound like a really cool idea. In fact CKEditor5 Core repository contains now 2 projects: UI and XXX. Both have separated MVC, share only utils and even, in fact, separated teams working on these projects. In makes a lot of sense to split it to "Core" and "UI". But it sounds like a huge refactoring...

**Comment by oleq** [comment]
DataLayer
DataEngine
...

**Comment by Reinmar** [comment]
OK, turns out we'll be doing some serious refactoring because of this issue :D More to come...

**Comment by Reinmar** [comment]
See #139. It answers the question I asked in this issue – there will be ( application + engine == core ), so the features will implement their core and UI parts.
