### ISSUE TITLE
Blank line at the end of the file - lack of consistency

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-design#146]
I have noticed that some of files contain a blank line at the end and some don't.
Probably there is no technical reason to keep blank line i our application, because each file is converted by gulp, but I think is worth to standardize it to avoid unnecessary diff in commits and frustrating warning on github 

![image](https://cloud.githubusercontent.com/assets/1057056/15066730/c556cd82-136b-11e6-95f0-fb8c4137f5d0.png)

My vote is to keep blank line. We can set this rule in `.editorconfig`.
What do you think guys?

**Comment by Reinmar** [comment]
+1. But we need to do more than just change the editor config file – we need a rule for JSCS or JSHint, add this rule in every existing repo (heh :D) and we may update the code style guide.

**Comment by Reinmar** [comment]
And of course I'm for having a blank line at the end.

**Comment by szymonkups** [comment]
Am I missing something or our `.editorconfig` has this option enabled already? https://github.com/ckeditor/ckeditor5/blob/master/.editorconfig

**Comment by szymonkups** [comment]
Still it would be nice to have it defined in JSCS/JSHint so the pre-commit hook could check it.

**Comment by pjasiun** [comment]
My fault, at least partially. Unfortunately Sublime does not handle this editorconfig option by default. Agree we could have JSCS/JSHint check enabled.

**Comment by Reinmar** [comment]
> Am I missing something or our .editorconfig has this option enabled already? https://github.com/ckeditor/ckeditor5/blob/master/.editorconfig#L12

Apparently Sublime does not read `.editorconfig`, so those of us who use it must configure this manually or install some plugin which adds such functionality.

**Comment by jodator** [comment]
@pjasiun: https://coderwall.com/p/icxxna/don-t-forget-that-extra-line Sublime config.

**Comment by oskarwrobel** [comment]
I think we can close it. We have a rule in [eslint config](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/eslint-config-ckeditor5/.eslintrc.js#L129-L132) and editorconfig.
