### ISSUE TITLE
Things naming conventions

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#15]
When coding CKEditor, several kinds of "things" need constantly to be named. We should try to uniformize these names.

This is the list of "things" to take in consideration:
- [x] 1. Default, for things not listed here:
  - lowerCamelCase
  - singular
- [ ] 2. Repositories: lower-case with dash ("-") separators.
- [x] 3. CKEditor specific repos: prefixed with `ckeditor5-`
- [ ] 4. Plugin:
  - repo: `ckeditor5-plugin-pluginame`
  - in-code name: lowerCamelCase
- [x] 5. Things named as strings that are to be consumed by end-developers, like plugin names, button names, configurations, event names:
  - case-insensitive when setting and retrieving
  - when written by us: lowerCamelCase

To take in consideration: casing, separators, singular/plural

**Comment by Reinmar** [comment]
I think that we have enough real examples now so when taking new decisions we can simply follow what we've done in the past :D.
