### ISSUE TITLE
Import from - relative or absolute path?

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-design#152]
We should follow two simple rules when we importing JS modules.
- **import path inside source files always must be relative** because our bundler `rollup` treats files with absolute path as external dependency and excludes it from bundle.
- **import path inside test files always must be absolute**, because bender + istanbul trows an error when parsing file with relative path (don't know why).

We can think about adding some rules to our code sniffer checking it.

**Comment by Reinmar** [comment]
Yep, we'd need a JSCS rule for that. We can create a ticket in ckeditor5 to not forget about it. It'd be nice if one of us know how to write JSCS rules. OTOH, [JSCS will be merged to ESLint](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint), so perhaps it's worth first to migrate to ESLint with all our configs (JSCS and JSHint). That'd be a bigger task though.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/437.
