### ISSUE TITLE
Commit message convention - present tense

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-design#153]
Right now we use past tense in commit messages:
```
Added parse-gitignore as a dep.
```

This is inconsistent with messages generated by `git`:
```
Merge branch 'master' into t/41
```
Apart from being inconsistent it might be also more error prone for non-native english speakers.

Relevant: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by scofalik** [comment]
I don't see this as a big thing, I can use whatever tense you will ask me. I tried to find if commit message was described anywhere but I failed.

**Comment by Reinmar** [comment]
We've always used past tense so the log is kind of a diary. Sometime we also use passive voice ("sth was done"). I got used to that and it's most intuitive for me at the moment.

However, if that's not a leading convention, we may consider switching. Especially if we'd like to use some automation tool for changelog/releasing. We can research both topics when we'll be working on releasing tools.

**Comment by maxbarnas** [comment]
@Reinmar Our commit messages are against established standards in many ways. Article added in the issue description (along with articles referenced in that article itself) shows how many things we have done in a different way. It is nothing critical, but worth looking at.

**Comment by Reinmar** [comment]
My point was exactly that we need to find such confirmation of common practices (which you've just done :)). So part of the research is done.

**Comment by maxbarnas** [comment]
I was proposing small change that was, at least for me, most helpful. But if there's room for general improvement in our commit methodology - then I should close this issue and open a more general one.

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-design/issues/30
