### ISSUE TITLE
Angular 2 WYSIWYG Editor integration #FeatureRequest

### ISSUE THREAD

**Issue by manuelfink** [ckeditor/ckeditor5-design#165]
I would really appreciate an strong integration of tinymce into modern web application frameworks. I believe both, angular 2 and reactjs are missing strong wysiwyg editor integrations.

Thus I'd really appreciate if you could provide an angular 2 component build for making integration easy.

Reposting this here, since I'm not sure whether it is besser located in the core or here in the design discussion (Just saw this after posting in the core). Original [post is in the core repository](https://github.com/ckeditor/ckeditor5/issues/347). Further technical considerations are available in my post in the core repository.

**Comment by Reinmar** [comment]
Let's continue the discussion in https://github.com/ckeditor/ckeditor5/issues/347. I think we'll close this repo for reporting issues and keep it for announcements to avoid confusion.
