### ISSUE TITLE
dialog boxes

### ISSUE THREAD

**Issue by kikkauz** [ckeditor/ckeditor5-design#179]
Hello

Does ckeditor5 allow at this stage to develop plugins with dialog boxes? I tried to search in the code and the documentation but I cannot find anything about it. Is it something alreaduy existing but still to be documented? If so, could you please point me to which part of the code implements it?
If no, why is it not in the roadmap? :-)

Thanks!

Kikkauz

**Comment by Reinmar** [comment]
Hi @kikkauz!

No, we don't use dialog boxes (also called "modal boxes") in the existing UI and hence we also haven't implemented such a [UI component](https://github.com/ckeditor/ckeditor5-ui/tree/master/src).

I'm not sure whether we have a single place where the decision to stop using dialog boxes (used heavily and for pretty much everything in CKE4) was explained. Maybe @oleq remembers some tickets.

Anyway, dialog boxes are heavily intrusive UI components and are also hard to do right (focus management for instance). As long as we won't need them, we won't use them. Contextual panels like these are better:

![image](https://user-images.githubusercontent.com/156149/29075834-eeeeae9c-7c53-11e7-92c6-feedf3b4cb44.png)

![image](https://user-images.githubusercontent.com/156149/29075840-f4ddefe8-7c53-11e7-86db-7765a342fe1c.png)

![image](https://user-images.githubusercontent.com/156149/29075848-fb4d987e-7c53-11e7-992c-b52f5ad4f773.png)

We can show them more frequently without disturbing the editing too much.

Therefore, there's no UI component for dialog box and we don't plan to create any. You could create one using the UI framework but if you can avoid that and just use contextual panels we think that it will be bettet.

**Comment by kikkauz** [comment]
Hello

thanks for the quick answer. 
I'll have a look at that hoping it can cover the uses cases I'll have to face.


Kikkauz

**Comment by oleq** [comment]
The issue was discussed in https://github.com/ckeditor/ckeditor5-design/issues/97.
