### ISSUE TITLE
Code style listing dependencies (AMD)

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#18]
There are two ways to list dependencies that we can take in considerations:

**One line**:
```js
CKE.define( [ 'ckeditor', 'tools', 'mvc/model' ], function( CKE, tools, Model ) {} );
```

**Multi-line 1**:
```js
CKE.define( [
    'ckeditor',
    'tools',
    'mvc/model'
], function(
    CKE,
    tools,
    Model
) {} );
```

**Multi-line 2**:
```js
CKE.define( [
    'ckeditor',
    'tools',
    'mvc/model'
], function( CKE, tools, Model ) {} );
```

We have these possibilities:

1. Always "One line".
2. Always "Multi-line".
3. "Multi-line" only if the line gets longer than a limit.
4. "Multi-line" only if a minimum number of requires is reached.

**Comment by Reinmar** [comment]
This got totally outdated - we're using ES6 modules now so there's no doubt how to format imports.
