### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#2]
The default strategy for grunt usage in our projects is described here:
https://github.com/ckeditor/ckeditor5-design/wiki/Grunt

The code implementation for this has been created here:
https://github.com/ckeditor/ckeditor5-design/blob/repos-boilerplate/gruntfile.js

**Comment by Reinmar** [comment]
Bye bye Grunt: https://github.com/ckeditor/ckeditor5-design/issues/117
