### ISSUE TITLE
HTML Code Style

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#24]
Just like the [JavaScript Code Style guidelines](https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style), we should have something for HTML.

**Comment by Reinmar** [comment]
We need some convention for ids and classes. Since classes must follow BEM it's quite clear how they need to be formatted. But what about ids? Camelcase or some other convention? Or does BEM clarify this as well?

**Comment by oleq** [comment]
> it's quite clear how they need to be formatted

Is it? Can you reference an issue/docs?

> Or does BEM clarify this as well?

Because everything should be re–usable, BEM considers IDs an anti–pattern, actually.

**Comment by Reinmar** [comment]
> Is it? Can you reference an issue/docs?

http://getbem.com/introduction/: 

> Naming invites us to use block--modifier--value syntax.

> Because everything should be re–usable, BEM considers IDs an anti–pattern, actually.

Sure, but we don't apply BEM e.g. to our manual tests.

**Comment by oleq** [comment]
> Is it? Can you reference an issue/docs?

I meant our docs.

**Comment by Reinmar** [comment]
We only talked about BEM in general: #64. No decisions have been made.

**Comment by Comandeer** [comment]
> But ok, there's no naming convention for the "block", "modifier" and "value" parts.
https://en.bem.info/method/naming-convention/

**Comment by Reinmar** [comment]
Ha! Good to know. So now we need to just pick one of the proposed convention and document it (plus convention for ids). @oleq?

**Comment by Comandeer** [comment]
Personally I'd also consider SUIT CSS, which is a superset of BEM: https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md

**Comment by oleq** [comment]
I'm against camel case in CSS. It's hard to read among HTML IMO. I'd stick to default convention from https://en.bem.info/method/naming-convention/.

**Comment by Reinmar** [comment]
I've just thought about the ids in context of the data model, where we decided to go with camel case. I think that it would be good to keep it consistent with HTML and all other types identifiers (such as variable names). All them should be camelcased.

**Comment by Reinmar** [comment]
> I'm against camel case in CSS. It's hard to read among HTML IMO. I'd stick to default convention from https://en.bem.info/method/naming-convention/.

So:

* Classes should be formatted according to BEM convention (hyphens between words, groups separated by `__`), yes?
* IDs should be camelcased to conform to general rules, yes?

**Comment by oleq** [comment]
> IDs should be camelcased to conform to general rules, yes?

I'd apply the same rules to IDs as well in the name of KISS.

**Comment by Reinmar** [comment]
I've got one more thought regardings ids. If we decide to go with camelCase then we make them hard to generate such ids programatically. E.g. some id may contain a key name like `ckDialog<dialog-name>`. On the other hand, I don't see us generating such ids because why would we need them... except that:

1. ARIA attrs often need them.
2. We already used kind-of-ids in icon names https://github.com/ckeditor/ckeditor5-theme-lark/blob/9e0b1d621edef7c4520164f8656f37b74a8fdb73/tests/manual/theme.html#L166.
3. Sometimes you need to create anchors and uppercase letters in urls don't look good.

So, I'm afraid I changed my opinion and would recommend `dash-separated-ids`. WDYT?

**Comment by oleq** [comment]
FYI: I updated design wiki with [CSS class and ID naming guidelines](https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines#css-classes).
