### ISSUE TITLE
Use CSS pre-processors

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#26]
We must decide whether we'll adopt a CSS pre-processor like [Less.js](http://lesscss.org/) or not.

**Comment by silkentrance** [comment]
I am currently reviewing a few WYSIWYG editors and came across this. Please stay with Javascript only, e.g. Less or some similar pre-processor. Personally, I think that this would be the best approach as we could also integrate this with for example Meteor without the need for an additional runtime such as Ruby (SASS, Compass).

**Comment by silkentrance** [comment]
As for the data-uri, I think that with LESS and proper macro logic and defined constants, selecting individual icons from a strip will be much easier.

**Comment by fredck** [comment]
@silkentrance, we're most likely going with Less, right because it's js.

Your suggestion about the macros make sense. We'll keep it in mind, thanks!

**Comment by silkentrance** [comment]
@fredck Great! Maybe you also have a look at Polymer and its meta component, which basically provides a lookup mechanism for defined constants and is also used for defining constants for said magic numbers, e.g. left and top offset into an image map.

**Comment by sgonyea** [comment]
Sass is great, and has a node interface to libsass (https://github.com/sass/node-sass)

One great thing about Compass is that it allows you to easily turn your image assets into sprites.  I'm actually dealing with making ckeditor4 less heavy on our site, and all the tiny image files are an issue... In addition to not being able to compile a subset of the plugins that we actually use.

So I'd strongly encourage Sass.  Regardless, thank you for making ckeditor! It's very well-done where it counts.

**Comment by jodator** [comment]
> Sass is great, and has a node interface to libsass (https://github.com/sass/node-sass)

@sgonyea I also think that SASS is great, but I think that the less external dependencies (non-node) the better. Also I found this disturbing:
> Compiling versions 0.9.4 and above on Windows machines requires Visual Studio 2013 WD. If you have multiple VS versions, use npm install with the --msvs_version=2013 flag also use this flag when rebuilding the module with node-gyp or nw-gyp.

As I don't use windows, it doesn't bother me, but CKEditor will be developed on Windows machines anyway, so I think that LESS is still safer choice in terms of interoperability.

Bottom line: +1 for LESS

**Comment by Reinmar** [comment]
> I'm actually dealing with making ckeditor4 less heavy on our site, and all the tiny image files are an issue... In addition to not being able to compile a subset of the plugins that we actually use.

Sorry for the OT, but this surprised me. Did you know about the CKBuilder which is available [online](ckeditor.com/builder) and in [command line](http://docs.ckeditor.com/#!/guide/dev_build)?

**Comment by silkentrance** [comment]
Since the sprite thingy seems to be very important: just found https://github.com/selaux/node-sprite-generator, which also includes template generation for less and grunt integration.

**Comment by Reinmar** [comment]
I guess it's high time to close this ticket. We use SASS through node-sass and we're pretty ok with it (I think, because fortunately, I don't write CSS :D). The only issue I know is the lack of `import_once` which causes us a lot of pain. E.g. https://github.com/ckeditor/ckeditor5/issues/420.
