### ISSUE TITLE
Globalization

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#28]
How we gonna implement internationalization into CKEditor 5 and what localization features we want to provide?

Short answer: the same as in CKEditor 4, just having all tools in node+grunt.

But, do we want to change anything else here?

**Comment by fredck** [comment]
A first version of the globalization documentation is available in the wiki:
https://github.com/ckeditor/ckeditor5-design/wiki/Globalization

It's a bit of blah blah blah... but may be important for those not used to globalization in general. The real shape of it will be given by the code that will be implemented to satisfy the requirements described there.

**Comment by fredck** [comment]
Additional translation service (for future reference):
https://crowdin.com/

**Comment by Reinmar** [comment]
If we'll implement the `t()` function as in https://github.com/ckeditor/ckeditor5-design/issues/136, then it will make the https://github.com/ckeditor/ckeditor5-design/wiki/Globalization totally outdated.

**Comment by Reinmar** [comment]
Cleaning up outdated discussions. See https://github.com/ckeditor/ckeditor5-design/issues/186
