### ISSUE TITLE
UI texts - review and document guidelines

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5-design#29]
There are plenty of issues with CKEditor 4 UI texts that we could improve, like:
- Make toolbar button tooltips uniform.
  We now have, for example,  Image, Table, Insert Horizontal Rule, Create Div Container, Insert Special Character, Smiley.
- Make dialog window names uniform.
  We now have, for example, Image Properties, Select Special Character, Insert Smiley, Code snippet and Mathematics in TeX.
- Use the same [capitalization rules](http://dev.ckeditor.com/ticket/12662) everywhere. This includes toolbar buttons, dialog windows, context menu entries etc.
- If a text is used in more than one place/ plugin, we should [add the strings to a common/core language file](http://dev.ckeditor.com/ticket/12294).
- Some toolbar and context menu icons (like B, I, U) could be [localized](http://dev.ckeditor.com/ticket/9419). (Also mentioned in #26 and #28).

Additionally, we should create rules for this stuff and adhere to them with each new feature that we add.

**Comment by Reinmar** [comment]
Cleaning up outdated discussions. See https://github.com/ckeditor/ckeditor5-design/issues/186
