### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#3]
The strategy for file naming is described here:
https://github.com/ckeditor/v5-protos/wiki/File-Names

**Comment by CanRau** [comment]
Maybe it's the wrong place, maybe it's already discussed somewhere. I just wanted to mention it.
I think ckeditor.js should be called ckeditor.min.js when downloaded the minified version. For clarification, and possible minification issues.
Just ran into one where the minifier tried to minify even though it's already minified but not reflected in the  filename..

**Comment by Reinmar** [comment]
Thanks for the idea. We should definitely keep that in mind (it's a part of the whole releasing topic, which we haven't yet started).

**Comment by Reinmar** [comment]
I opened #145 for aspects related to releasing.
