### ISSUE TITLE
Commits messages convention

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#30]
We should have some rules for commit messages. I propose:
- Use past simple to describe changes ("Added new method.") or present simple to describe state after changes ("Method fire event.").
- Each sentence in commit message should begin with a capital letter and end with a full stop.
- Start sentence with "Added..." when new variable, method, event etc. have been added.
- Start sentence with "Fixed..." when some bug have been fixed.
- Start sentence with "Removed..." when variable, method, event etc. have been removed.
- Start sentence with "Renamed..." when variable, method, event etc. have been renamed.
- Use "Tests." or starts commit message with "Tests: ..." when changes touch ONLY tests, when commit touch code and tests, changes in code should be described as first.
- Use "Docs." or starts commit message with "Docs: ..." when changes touch ONLY docs, when commit touch code and docs, changes in code should be described as first.
- Use "Code style." or starts commit message with "Code style: ..." when changes touch ONLY code style, when commit touch code and style, changes in code should be described as first.

**Comment by vokiel** [comment]
Sorry for digging this out.

At the WDW there was an post about longer comits messages https://web-design-weekly.com/2013/09/01/a-better-git-commit/

Personally I like the idea - 1 line of short description, then another lines with more explanation (if needed). Of course sometimes there is nothing more to add than the first line, but on the other hand there are cases where more descriptive message is a huge help for the reader to understand what the code does, what changed. And the last thing - I don't like how GH splits the commit message when it's too long - so 72 chars limit for the first line seems to be the right way to go.

One rule more I would add:
> Don't end the summary line with a period - it's a title and titles don't end with a period.

Another link worth reading http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by Reinmar** [comment]
We described our convention in https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention.
