### ISSUE TITLE
Plugins Overview

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#33]
A brief overview about plugins is described here for documentation:
https://docs.google.com/document/d/1PMmQStkM6kBNqbnF56PDX2fWLw2mfDotoF9qEQfwavA/edit?usp=sharing

**Comment by fredck** [comment]
Updated the "Asynchronous Initialization" section:
https://github.com/ckeditor/ckeditor5-design/wiki/Plugins#asynchronous-initialization

**Comment by Reinmar** [comment]
> Updated the "Asynchronous Initialization" section:

+1.

**Comment by fredck** [comment]
As for now we can consider the current documentation sufficing to start the development.
