### ISSUE TITLE
Static analysis, metrics, code complexity visualisation tools

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#35]
I stumbled upon https://github.com/es-analysis/plato yesterday, but I remember that there was a least one interesting tool besides this one (https://codeclimate.com/ IIRC).

I would like to integrate one of the tools in our workflow. Such tool doesn't do any magic - it just stresses out the obvious. For example using Plato I found out that `range.js` is the least maintainable file with complexity out of charts. No surprise :D.

The history cannot be undone easily, but if we used such metrics from the beginning and have some limits set, then perhaps few things would be implemented differently.
## About Plato

Pros:
- I don't know how but it can gather historical stats. Perhaps it does not override generated stats, but adds to them. This is nice.
- It was easy to use and it generates static files.
- Check out the examples: https://github.com/es-analysis/plato#example-report-on-popular-projects
  - Note that there's a project view with all files as well as stats for each file (e.g. http://es-analysis.github.io/plato/examples/jquery/files/src_css_support_js/index.html) 

Cons:
- Chrome crashed when I tried to load stats for one of our files. Well... it was complex, but not so much :D.
- The file view isn't stable. For some reasons I can't check complexity of some functions.

Still, even with these problems this is a pretty nice tool. If nothing else beats it I would go with it.

**Comment by Reinmar** [comment]
Another app - https://www.bithound.io/ (and https://www.bithound.io/github/ckeditor/ckeditor-dev). It might be nice, but it's so terribly slow, that I cannot see anything (e.g. this does not load for me https://www.bithound.io/github/ckeditor/ckeditor-dev/master/files#priority).

**Comment by Reinmar** [comment]
Before going more public with our repos it will be nice to get back to this topic and introduce more badges and stats for our repos.

E.g. I checked that BitHound works better now https://www.bithound.io/github/ckeditor/ckeditor5-engine. But I'd check all of them again.

**Comment by maxbarnas** [comment]
Let's assume we have right tool for code analysis - how would we change our workflow to actually make us of that tool? Another step in before code review?

**Comment by Reinmar** [comment]
We used Codeclimate for a while, but it wasn't much of a help. We'd need first to define what kind of statistics we really need, based on some real issues we have. Then we can think on what tool to use.  Code smell is low in our code anyway due to reviews, linters, tests, etc, so most of the things at which Codeclimate pointed out where not really issues or were issues we decided are not relevant.
