### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#43]
Out final position must be taken when it comes to use [Promises](https://promisesaplus.com/) in CKEditor 5.

We're most likely to go with them and in fact #33 depends on this to be closed.

**Comment by gregpabian** [comment]
I'll just leave it here: https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns (it might be useful at some point).

**Comment by fredck** [comment]
Documentation has been added to our Wiki:
https://github.com/ckeditor/ckeditor5-design/wiki/Asynchrony-and-Promises

**Comment by Reinmar** [comment]
Another interesting bit – http://jamesknelson.com/are-es6-promises-swallowing-your-errors/. Especially:

> Happily, there is a library which makes this easy! Bluebird provides a simple fix which easily integrates with your existing code by extending the ES6 Promises API.
> 
> After installing bluebird, you can make sure you know about unhandled rejections by adding the following three lines:
>
> Promise.onPossiblyUnhandledRejection(function(error){
>    throw error;
> });

**Comment by fredck** [comment]
@Reinmar, the Chrome dev console has been very useful on catching and showing errors on promises, so I'm not sure this is a real problem.

**Comment by pjasiun** [comment]
One more prove that we need logging/debugging module in CKE5.

**Comment by Reinmar** [comment]
@fredck, I have no experience with this, but if an article was written perhaps it's a real problem. For instance, I can imagine that we would like our tests to fail whenever an error isn't handled in a promises chain. For that we can integrate our test runner with the Bluebird's feature. Also, Chrome may log uncaught errors, but what with other browsers?

**Comment by Reinmar** [comment]
Related ticket in the CKE4's issue tracker – http://dev.ckeditor.com/ticket/13546

**Comment by SteveTheTechie** [comment]
http://complexitymaze.com/2014/03/03/javascript-promises-a-comparison-of-libraries/
http://calvinmetcalf.com/post/85041743853/comparing-promise-libraries
