### ISSUE TITLE
Testing: Tagging

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#44]
The [Testing page](https://github.com/ckeditor/ckeditor5-design/wiki/Testing) should have a section about "tagging". To complete it, we should come with the proposed list of tags, to be agreed here.

**Comment by Reinmar** [comment]
This is so outdated now, that I'll rather close this ticket :D Besides, we lost the tagging option when we dropped Bender so we'll be rethinking the whole thing in the future. Most likely, with a first releases where we'll do real testing phases. So, the whole process is yet to be defined.
