### ISSUE TITLE
Testing: Manual Tests

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#46]
The [Testing page](https://github.com/ckeditor/ckeditor5-design/wiki/Testing) should have a section about "manual tests". We need to come to an agreement on how we see and use them in CKEditor 5. I understand that there are new proposals based on the v4 experience.

**Comment by Reinmar** [comment]
Cleaning up outdated discussions. See https://github.com/ckeditor/ckeditor5-design/issues/186
