### ISSUE TITLE
Dependencies between plugins - is package.json the right choice

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#48]
I don't know if this doubt appeared before, but I've just stumbled upon:

* https://twitter.com/wycats/status/545292896773996544
* https://twitter.com/wycats/status/545307887380090880

And it make me realise that we'll have the same problem in CKEditor. If we decide to specify plugins requirements in the `package.json` it will be a total madness. Each plugin will be exist in the file system the number of times it is listed in other plugins' `package.json` files.

If, during the development, we'll use `npm link` that will be just a network of symlinks. But when an "end-developer" will clone the `ckeditor5` repo and run `npm install` then the explosion happens. It may not be that big issue, because it's just some space on your disk, but I wonder how much in case of ~50 plugins (what may be real). I'm also curious about another thing - circular dependencies (plugin A requires B, B requires C, C requires A) - is npm able to handle that?

Refs:

* https://github.com/ckeditor/ckeditor5-design/wiki/Plugins
* #33.

**Comment by fredck** [comment]
Later on, if npm will not have dependencies' directories flattened, we can think about loading `package.json` from each individual plugin/resource recursively through the dependency tree. It may have an "acceptable" performance in a development environment.

**Comment by Reinmar** [comment]
Since we implemented a [builder](https://github.com/ckeditor/ckeditor5-design/wiki/Building) and npm started deduping packages, things got much simpler. The [Building](https://github.com/ckeditor/ckeditor5-design/wiki/Building) article describes what are the erroneous cases in which the builder should throw an error.
