### ISSUE TITLE
Less reusable internal functions more static ones.

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor5-design#51]
When I read https://github.com/ckeditor/ckeditor5/issues/15 I found out that we still (reproduced pattern from v4) create internal functions which might be added into some `tools` and be [reusable](https://github.com/ckeditor/ckeditor5/blob/master/tests/ckeditor/basepath.js#L69-L85)

If we create new function we should ask ourself a few questions:
- Whether it might be reusable in other components?
- How much it impact object withing this method is created? (Doesn't have nothing or little to do with `this` property)

If function is a good candidate to be reusable and doesn't impact object within is created, we should consider adding it into tools or as a static property.

With this in mind it's a great way to build very rich API.

**Comment by fredck** [comment]
@adelura, can you edit the description using an immutable URL to point to lines of code (like [this](https://github.com/ckeditor/ckeditor5/blob/678797adad1aa666ef82def6a7f6f1a90835591f/tests/ckeditor/basepath.js))?

**Comment by fredck** [comment]
I agree... but I don't think this is the case for the functions you pointed out. Hopefully we'll not any more have to do those hacks in other tests.

**Comment by Reinmar** [comment]
This has changed a lot since we begun our journey with the new code base but we still make public only what needs to be public :) However, since we code things differently now (in a far more modular way) more things need to be public, so the API is indeed bigger.
