### ISSUE TITLE
Use package.json for plugins' metadata

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#56]
In v4 we inject some "metadata" about the plugin inside the plugin code itself. For example, we add the `lang`, `icons` and `hidpi` properties to the plugin definition, which are used during development to properly load plugin resources and at the same time by the builder, in a hacky way, to include such resources in the build. These properties are them removed from the build, again in a hacky way.

It looks like we'll need something similar in v5. What about using `package.json` for this instead? We could reserve an addional `"ckeditor": {}` entry in it with metadata that is related to CKEditor.

The cool thing about this is that we would have the possibility to access much more information about the plugin, like its description, the author name, license information, homepage, etc.

This means though that plugins authors would be required to have the package.json file, using them npm or not.

**Comment by Reinmar** [comment]
We don't need any metadata for now, but if we'll need, we'll certainly use package.json.
