### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#57]
The overview about "Data Processing" has been documented here:
https://github.com/ckeditor/ckeditor5-design/wiki/Data-Processing

Comments are welcome before making this final.

**Comment by fredck** [comment]
After a talk with @gregpabian, we understood that some things in the proposed documentation are wrong. I'll be working further on it.

**Comment by fredck** [comment]
Ok, changes applied to the document.

**Comment by fredck** [comment]
Introduced also a brief explanation about the "Document Model" here:
https://github.com/ckeditor/ckeditor5-design/wiki/Document-Model

**Comment by fredck** [comment]
Ok, I've removed the reference to the Document Model, which should be handled separately. I'm asking for review on the Data Processing page again.

**Comment by Reinmar** [comment]
It's OK now. I only started thinking where do we want to normalize e.g. `<font>` tags to something valid. E.g. someone pastes to the editor a content that could've been copied from some legacy website. At which point `<font>` will be recognised as a fg/bg/size attr? By converters? I think that it sounds good but perhaps it requires some clarification in the document.

**Comment by Reinmar** [comment]
Other than that – R+.

**Comment by fredck** [comment]
> It's OK now. I only started thinking where do we want to normalize e.g. <font> tags to something valid. E.g. someone pastes to the editor a content that could've been copied from some legacy website. At which point <font> will be recognised as a fg/bg/size attr? By converters? I think that it sounds good but perhaps it requires some clarification in the document.

The document seems to be clear enough specifying that this is all about the data inputted on load and outputted on destroy. Nothing seems to be related to tasks performed during editing (like pasting).

I think that you doubt seems to be more something that we have to think about as we know well the pieces we have to work on, but as for a reader of that page exclusively, I don't think that doubt would come.

We can enhance this in the future if we'll not find a better place to clarify that.
