### ISSUE TITLE
Multiple Editables

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#58]
We've been discussing about the possibility of having one editor instance which is attached to more than one editable. The [current design](https://github.com/ckeditor/ckeditor5-design/wiki/Editor-Instances) doesn't support this as it requires one single "root" editable which could then contain many editables.

Let's take for example a case where we want one editor to handle editables around different places in a page.

The problem with the current approach is that we would have to set an outer element, like `<body>` as the root editable (with editing disabled) and then set new editables for each desired region. By doing so, we would have to process the whole body element, replacing it with the processed data even if we're not interested on editing it.

The new idea is making it possible to add as many editables as one wants directly to the editor, without having any hierarchy among these editables.

**Comment by fredck** [comment]
We could have an API similar to the following:


```
// Creates a single editor.
editor.create( element );

// String for selectors. Converted with querySelectorAll().
editor.create( '#content' );
editor.create( '.areas' );

// Iteratables are accepted.
editor.create( document.getElementsByTagName( 'textarea' ) );
editor.create( document.querySelectorAll( 'div.title, div.content' ) );
editor.create( [ element1, element2 ] );
```

```
// `config` overrides on top of parent.config.
editor.editables.add( editable/element, config );

editor.editables.remove( editable );

// Defaults to editor.editables.get( 0 )
// Change on focus.
// Fires "current".
editor.editables.current;
```

```
// Proxy to editor.editables.current
editor.setData();
editor.getData();
```

```
// Editables nesting.
editable.editables;

// Inherits from parent (editor or editable)
editable.config;

// Each editable have its own Document Model.
editable.dm;
```

**Comment by pjasiun** [comment]
I like the idea (surprise, surprise), but.

```js
// Defaults to editor.editables.get( 0 ).
// Change on focus.
editor.editables.current;
```
I do not think that `current` should change on `focus`. If user will focus nested editable, `editor.setData()` should still be called on the '`root`', so the `current` should not change. We could tread top level editable differently then nested but I think that it is unnecessary. And, even talking only about top level editables, it would be awkward if `editor.setData()` change its target based on where user clicked (focus change). Lets keep it simple, if one want to change the current editable on focus it will take 3 lines of code.

Second. The behavior of these:
```js
editor.create( '.areas' );
editor.create( [ element1, element2 ] );
```
should depend on what creator was used. It will create one editor with multiple editable for `multipleEditables` creator (or whatever it will be called), but for `classic` creates only one or throw an error if the selector returns more then one element (what is imho a better behavior).

**Comment by fredck** [comment]
I'm proposing this at ckeditor/ckeditor5-core#27. I'll update the documentation and close this issue once we have that PR closed.

@pjasiun, to follow up on your comment:

 * For now I'm not introducing anything related to focus. This will be introduced in the future. If we would ever change "current" based on that, we would definitely take in consideration the "top level" editable only (children of the editor instance directly).

 * Yes, I've implemented it in a way that the classic editor throws an error is multiple editables are available.

**Comment by Reinmar** [comment]
This got seriously outdated. In short – the engine supports multiple editables. If you want your editor to support multiple editables, you need to create its API in a way that it knows what to do with the elements you pass to it. Since there are no restrictions on editor API you can do it however you want. The most popular editors like the [classic editor](https://github.com/ckeditor/ckeditor5-editor-classic) or [inline editor](https://github.com/ckeditor/ckeditor5-editor-inline) support just one editable.
