### ISSUE TITLE
Data API naming

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#59]
![image](https://cloud.githubusercontent.com/assets/1166967/7880242/11b05068-05f8-11e5-885f-e48dfaf75e01.png)

We need to give our children names. We will take care of them for a few years. 

At the moment we have a naming collision issue:
- `document` means both DOM document and model document (which contains both linear data and document tree) and most probably we may have a DOM document wrapper too,
- `data` is linear data and the data we will put to `setData`, so the (input) data will be transformed to HTML and it will be transformed to (linear) data,
- `attribute` is an HTML attribute or linear data attributes,
- `Node` is DOM node and document model node (which can refer to multiple DOM nodes in case of the `TextNode`), but the parent of the DOM node is `element` while the parent of the document model node is `branch` at the moment. And again, we may have a DOM node wrapper too.

We need some unique names, I believe the even some random letter are better then the collided name (see `acf` is better then one more `filter`). And the same names should be used everywhere: in the code, comments and documentation.

Think about writing a documentation for transformation DOM node to document model node. We need one way how we call them, so users do not need to guess if 'document node' is 'model node' or 'DOM node'. And, of course, reading the code where you have just `node` variable is unnecessarily hard. 

We could use prefixes like we do now for native elements. So `$node` will be a native node, `Node` will be a data model node and `DOMNode` will be a native node wrapper. We could use "Native Node", "Model Node" and "DOM Node" in the text.
For document it can be the same: `$document`, `DOMDocument` and `Document`, but maybe we could find the better name for the last one. `DocumentModel` or `Model`?
For data: `data` for input data, `linearData` for the whole structure and `linearDataItem` the the item: letter, opening or closing tag (no `ldi` because lower "L" is bad in such shortcut),
For attributes: `$attribute` and `linearDataAttribute`.

But I hope we can find something better together.

**Comment by pjasiun** [comment]
We decided that all names related to the native elements will be prefixed with `$`, related to wrapped native elements will be prefixed with `w` and document model elements will have no prefix, so:
 - `$element` is native DOM element,
 - `wElement` is wrapped DOM element,
 - `element` is Document Model element.

The same way we have:
 - `$document` - native DOM document, also `$attr`, `$evt`
 - `wDocument` - wrapped DOM documet, also `wAttr`, `wEvt` (if needed)
 - `document` - Data Model Document, also `attr`, `evt`.

Moreover there will be `wrap()` function to create a wrapped element based on the native one.

The only part which is not yet agreed is how to distinguish input data and Data Model data.

**Comment by Reinmar** [comment]
> We decided that all names related to the native elements will be prefixed with $, related to wrapped native elements will be prefixed with w and document model elements will have no prefix, so:

And we never did that :)
