### ISSUE TITLE
Creating classes

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#62]
We should chose the way we will create classes in CKEdior5.

We could use always our `BasicClass`, so the `BasicClass` will be the parent of all classes (Java style):
```js
var Foo = BasicClass.extend( {
		constructor: function Foo() { /* ... */ },
		bar: function{ /* ... */ },
		/* ... */
	} );
```

We could use classic JavaScript when we don't need to have a parent class:
```js
function Foo() { /* ... */ }
Foo.prototype.bar = function{ /* ... */ };
```

Or we could use ES6:
```js
class Foo {
  constructor() { /* ... */ },
  bar() { /* ... */ }
}
```

I like the idea of having one base class, so every class will be created the same way. The code will be more consistent and we will not need to change anything if any class will need to be a base one day (every class will have an `extend` method).

But I think also that it is more a matter of style, and most of all, we need to establish some rules, because we will have a mess otherwise.

**Comment by fredck** [comment]
The only way to replace the classic JavaScript way to create a class without inheritance would be doing something like `EmptyClass.extend( ... )` which is weird. Forcing inheritance for the only purpose of coding style is pointless.

The only real solution is ES6 classes, but the adoption of ES6 is another big topic of discussion.

**Comment by pjasiun** [comment]
I do not think it is weird. It is pretty popular for me that there is one base class for everything, but maybe it's because of Java background.

**Comment by fredck** [comment]
> It is pretty popular for me

Hahaha... nice try :D

**Comment by pjasiun** [comment]
At least I tried ;)

**Comment by pjasiun** [comment]
We decided to give a try ES6 classes: https://github.com/ckeditor/ckeditor5-design/issues/63.

**Comment by oleq** [comment]
I'm totally for ES6 classes. First of all I'm tired of CKE3+ approach, things like `CKEDITOR.tools.createClass()` etc. Secondly, ES6 classes are what makes ES6 accessible to developers who are not quite into JavaScript, people afraid or confused by the prototype–based inheritance. Classes in ES6 have been designed to make their work easier and to make JavaScript more friendly. I think it would be a silly decision just to drop it.

**Comment by Reinmar** [comment]
The whole code is now based on ES6 classes and there's not much to add and document.
