### ISSUE TITLE
License information in package.json

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#66]
Since [npm accepts SPDX expressions for the license information](https://github.com/npm/npm/issues/7091#issuecomment-120803946), we must update `package.json` accordingly.

**Comment by Reinmar** [comment]
We use:

```js
  "license": "(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)",
```

hopefully everywhere.

**Comment by fredck** [comment]
I'm afraid the proper license is:

```
"license": "(GPL-2.0+ OR LGPL-2.1+ OR MPL-1.1+)"
```

**Comment by Reinmar** [comment]
I followed CKE4: https://github.com/ckeditor/ckeditor-dev/blob/44fe56dfbdfa229a142583c54ad8625b3a107272/package.json#L29

@mlewand, are you sure about it?
