### ISSUE TITLE
Name for a collection of transactions and a builder

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#68]
Context. The only way for changing document is to apply transaction. Transaction is a set of operations (retain 5, insert 'f', insert 'o', insert 'o'). The `applyTransaction` will return the set on modified nodes which should be render later.

Many times one feature will need to apply multiple transactions (insert new paragraph, insert text into this paragraph). All of them together will be a single undo step and changes will be render together too. 

Also instead of creating transaction manually we need some kind of helper, so developer will call simply `createChildElement( parent, 'p' )` instead of thinking about `retain` and `insert` operations.

Now we need a good name for such collection of transactions and a builder.

If they will be called `Modification` and `Builder` the code will looks like this:
```
var builder = new Builder( document );
builder.addAttribute( range, bold );
builder.modification.render();
```

But maybe you have a better name. 

Instead of `Modification`: Alteration? Change? Transactions?

Instead of `Builder`: Writer? Novelist? :)

This will be the main class to do any type of change in the document so it would be good to have a proper name for it.

**Comment by jodator** [comment]
Other ideas:

```js
var builder = new StepBuilder( document );
builder.addAttribute();

var step = builder.build(); // or builder.getModification();

( new StepRender() ).render(step);
```
Reason: Builder builds `step`/`modification` which might be rendered later or added to undo/redo.
But hits is only by judging `builder.modification.render()` alone.

Names:
- `Step` - group of transactions
- `StepBuilder` - builder for a group of transactions.
- `StepRenderer` - somethinig that will render whole step (each transactions at once).

**Comment by Tade0** [comment]
"Many times one feature will need to apply multiple transactions"
Why should there be multiple transactions? Are we expecting something to happen between them?

**Comment by pjasiun** [comment]
No, the transactions here is the transaction in terms of operation transformation, not database. In fact we could merge them, but it would be useless work. Also once we merge them we would not be able to separate them later if we want to rollback only part of the change. Additionally modification/step contains also the collection of added/removed/modified nodes what should not be a property of the transaction. But I cannot deny that I was thinking about merging transactions.

**Comment by zaak** [comment]
```js
var builder = new ModificationQueueBuilder( document );
builder.addAttribute( range, bold );

var modificationQueue = builder.buildQueue(); // returns ModificationQueue, a kind of collection object with specified target element

var renderer = new Renderer();
renderer.render(modificationQueue);
```

**Comment by Tade0** [comment]
>No, the transactions here is the transaction in terms of operation transformation, not database

I'm referring to the general notion of a "transaction" as an indivisible operation.

> Also once we merge them we would not be able to separate them later if we want to rollback only part of the change.

Could you give an example when would we want to this?

>Additionally modification/step contains also the collection of added/removed/modified nodes what should not be a property of the transaction.

What happens to this data when we rollback one of the transactions in the collection?

**Comment by pjasiun** [comment]
@jodator @zaak: I like your idea of the separate `Renderer`. But I am afraid that there will be too much code to write for each change. Note that `Builder` will be used every time anybody wants to change the Document. Changes need to be saved in the undo manager and rendered, every time. 

But anyway `Renderer` is good code separation, so even if there will be some shortcut it will use `Renderer` anyway.

**Comment by pjasiun** [comment]
Some documentations about operation transformation call set on operations `Delta`. We could use this name so the set of operations will be called `Delta`. Then the set of `Delta`s could be called `Transaction`.

**Comment by jodator** [comment]
@pjasiun `Delta` is a good name.

**Comment by scofalik** [comment]
+1. I was going to comment that `Transaction` is actually a better name for that set, but did not come up with a better name than `Transaction`, so I didn't comment after all. `Delta` sounds good.

**Comment by pjasiun** [comment]
I like delta because of one more (maybe a little weird) reason. It sounds scientific, mathematical, and is good name for a class on the scientific/mathematical level of the interface which is operation applying and transformation.

**Comment by scofalik** [comment]
I like `Delta` because, because math background, for me it is a synonym of "difference". I think it fits great.

**Comment by pjasiun** [comment]
The future comments should go to https://github.com/ckeditor/ckeditor5-core/issues/69, if needed.
