### ISSUE TITLE
ES6 Proxies for the config

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#70]
With ES6 Proxies we could have something link this:

```
var config = Config();
config.img.width.max = 100;
```

Since ES6 proxies are not well implemented yet (they are implemented only in Edge and Firefox), this is an idea for the future.

**Comment by fredck** [comment]
This may not fit or be a clear enhancement for the [current configuration API](https://github.com/ckeditor/ckeditor5-design/wiki/Configuration), but this can be evaluated in the future.

**Comment by Reinmar** [comment]
The future proved that this isn't necessary. We have so little config options (and plan to have) that the API is quite irrelevant. Besides, Proxies are hard to transpile (I'm not sure Babel supports them).
