### ISSUE TITLE
Automatic Sinon spies/stubs restoring

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#72]
I want to propose that everytime we create a Sinon spy or stub that needs to be restored before the next test executes we use [Sinon sandboxes](http://sinonjs.org/docs/#sinon-sandbox) like this:

```
var sandbox;

beforeEach( function() {
    sandbox = sinon.sandbox.create();
} );

afterEach( function() {
    sandbox.restore();
} );

it( 'whatever', function() {
    sandbox.stub( obj, 'foo' );
} );
```

I've been also considering extending `benderjs-sinon` with something like this (note, it must be testing framework agnostic):

```
afterEach( bender.restoreSpies() );

it( 'whatever', function() {
    bender.spies.push( sinon.stub( obj, 'foo' ) );
}
```

It'd be shorter, but it isn't that much simpler, so the default Sinon way looks satisfying.

Any thoughts?

**Comment by pjasiun** [comment]
```
var sandbox;

beforeEach( function() {
    sandbox = sinon.sandbox.create();
} );

afterEach( function() {
    sandbox.restore();
} );
```
This looks like a repeated piece of code. So it should be defined one in the sinon or ckeditor bender plugin. DRY.

**Comment by Reinmar** [comment]
@pjasiun wrote in priv chat:

> The problem is that sometimes we define spy for the whole test suit and sometimes for a single test

This is something I've been also aware, so I rejected things like https://www.npmjs.com/package/mocha-sinon which tries to automate the thing too much (I like to have a choice :D). The test author should be able to decide what should happen with a specific spy/stub. Both solutions that I proposed above allow you to make that decision.

On the other hand, one could argue that spies/stubs should never ever be shared between tests. This is also totally valid, so IMO we should avoid sharing them between tests. However, it's good to have a choice.

**Comment by Reinmar** [comment]
> This looks like a repeated piece of code. So it should be defined one in the sinon or ckeditor bender plugin. DRY.

The problem here is that it cannot go to benderjs-sinon or benderjs-mocha, because it's a link between those two plugins. That's why in the solution I was going to propose you need to call `afterEach()` manually. So `bender.restoreSpies()` is exposed by the benderjs-sinon plugin and `afterEach()` of course by benderjs-mocha.

However, if we want to be super strict about DRY, then we can add something to CKE's plugin for Bender. But I'm not a big fun of this solution as you'll start repeating that in other projects using Bender and Sinon.

Therefore, I think that we need some simple mechanism and a convention. If you think that Sinon sandoboxes violate DRY, then perhaps the second option is fine?

**Comment by Reinmar** [comment]
I'm also checking if that could work (first tests are promising):

```
var sandbox = sinon.sandbox.create();

afterEach( sandbox.restore.bind( sandbox ) );
```

**Comment by Reinmar** [comment]
It seems to work fine. I'm OK with this approach.

**Comment by Reinmar** [comment]
We take care of this manually.
