### ISSUE TITLE
Clarify what you're supposed to do on 3 stages of plugin initialisation

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#75]
There are 3 stages:
1. Static (directly inside module definition) – code executed only once for all editors.
2. Inside plugin constructor – code executed for every editor.
3. Inside plugin's `init()` method – code executed for every editor right after plugins are constructed (may this change in the future?)

The wiki article: https://github.com/ckeditor/ckeditor5-design/wiki/Plugins

It's a bit unclear even for me what's the difference between step 2 and 3. The 3rd step allows you to do async stuff and you can be sure that instances all other plugins are already available in `editor.plugins`, so if you need their instances or you need to do something asynchronous, then you'll definitely want to use the `init()` method. But other than that it's not clear if we meant something special, so I think this should be documented.

**Comment by fredck** [comment]
> The 3rd step allows you to do async stuff and you can be sure that instances all other plugins are already available in editor.plugins

Yes, that's the whole point about it.

**Comment by Reinmar** [comment]
Cleaning up outdated discussions. See https://github.com/ckeditor/ckeditor5-design/issues/186
