### ISSUE TITLE
Abstract methods

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-design#81]
In ES6 there is no mechanism to handle abstract methods. This is a useful programmatic concept, that we could already use in some places in the code. We have an `Operation` class which is a base class for all other operations, like `InsertOperation` or `MoveOperation`. Every class that extends `Operation` should define two important methods: `_execute()` and `reverseOperation`. Pretty soon we will also have `getTransformedBy` method.

It would be useful both for coding and debuging if we agreed on a solution to handle those abstract methods. I propose following:

```
class MyClass {
  abstractMethod() {
    throw CKEditorError(
      'myclass-abstractmethod-not-defined: Method abstractMethod ' +
      'has not been defined for class ' + this.constructor.name,
      { instance: this }
    );
  }
}
```

We could also use the following code for abstract classes:
```
class MyClass {
  constructor() {
    if (new.target === MyClass) {
      throw CKEditorError(
        'myclass-abstract-class-instantiated: Cannot instantiate abstract class MyClass.');
    }
  }
}
```

Opinions?

**Comment by pjasiun** [comment]
:+1:

We could also use some annotation so these abstract methods will be removed during minimization.

And that is very useful that when one want to add one more instance on that class he knows what methods needs to be implemented.

**Comment by Reinmar** [comment]
I don't feel like this is necessary. If we expect that developers will fail to notice that they didn't implement some class correctly (despite the documentation clarifying this), then we may occasionally use this idea. But in most cases I wouldn't go that far. Especially that to not affect the code size we would need to implement also a mechanism in the builder which would remove them. But that would result with a different behaviour in both envs, problems with code coverage (you need to test those abstract methods and constructors or mark them to be ignored), etc.

**Comment by Reinmar** [comment]
I'm closing this issue, because this topic hasn't come back since then.
