### ISSUE TITLE
Let it go.

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#83]
What do you think about replacing `var` with `let`? See https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/ for details about differences.

We used to use `var` and used to quirks. But in 5 years our code with `var` may contains unneeded quirks which we will not be able to remove easily.

On the other hand `var` have better performance and `let` is not supported everywhere, but we could use Babel.

**Comment by oleq** [comment]
> What do you think about replacing var with let? 
It should be used where it matters. In loops to avoid unnecessary `(function(){})()` closures and the like. It's not like a choice whether use `var` or `let` – both have meaning and clear applications and must be used intentionally.

> On the other hand var have better performance
Note that it will change. ES6 is something new in the web browsers and still things will get optimised, better and better. It's just a matter of time. Also note that it is DOM, that usually slows down the applications, not JS.

Besides, as I said in the previous response, it's up to the developer to decide whether to write things shorter of a little bit faster.

> and let is not supported everywhere, but we could use Babel.
We must code using everything which is supported at the moment and update "old" code when the new ES6 features get implemented.

**Comment by Reinmar** [comment]
Short but worth reading: https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

**Comment by Reinmar** [comment]
I'll create tickets in ckeditor5 and ckeditor5-core to convert the codebase to `let/const`.

In general, I would propose prohibiting using `var` unless you can come up with an example where you would like `var`'s behaviour. I cannot.

**Comment by oleq** [comment]
> Short but worth reading: https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

It's more or less what I meant in https://github.com/ckeditor/ckeditor5-design/issues/83#issuecomment-153703001.

**Comment by pjasiun** [comment]
> It's not like a choice whether use var or let

 I do not like the idea of mixing `var` and `let`. It would be messy and the opportunity to make a mistake.

> In general, I would propose prohibiting using var unless you can come up with an example where you would like var's behaviour. I cannot.

So :+1:

**Comment by scofalik** [comment]
Okay. Should we rewrite everything that is on master and development branches?

**Comment by Reinmar** [comment]
> Okay. Should we rewrite everything that is on master and development branches?

I will handle ckeditor5, ckeditor5-core and plugins. Then I'll ask you to update your branches. But not earlier, so we can have necessary discussions based on my changes. In other words – after my changes land on master branches, nothing "old" can be merged, so PRs and existing will need to be fixed before merging them.

**Comment by oleq** [comment]
Anyway, I found some interesting comment about `let vs var` http://programmers.stackexchange.com/a/274352.

**Comment by wimleers** [comment]
Love the issue title :D
