### ISSUE TITLE
Headless editor

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#86]
I propose to make it possible to create "headless" editors. In other words, editor instances that have no elements, no editables, no UI.

The idea is making it possible to use the CKEditor API so one can programmatically take benefit of its infrastructure. For example, one could load data into it for filtering or manipulation. Features could be executed in content with the very same behavior they have in the browser.

**Comment by fredck** [comment]
One of the main benefits of this feature would be enabling the CKEditor API inside Node.js (#87).

**Comment by wimleers** [comment]
+1000

If there is *something* CKEditor can do to increase its appeal to front-end developers, it's by doing this. This is going a step further than "we provide a default UI that you can override with your own": this means CKEditor can literally become the standard engine in most editors.

In other words: with this, you will have maximized the probability that people outside CKSource will contribute in significant ways.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/438.
