### ISSUE TITLE
Code style rules for arrow functions

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#90]
I can't see [JSCS rules](http://jscs.info/rules?q=arrow) that would suite us yet, but I want to propose these rules anyway:
## OK:

```
x.map( item => item.foo );

x.reduce( ( item, map ) => map.set( item.name, item ) );

x.reduce( ( map, item ) => {
    map.set( item.name, item );
} );

x.on( 'change:item', ( item ) => {
    // do sth
    // do sth
    // do sth
} );
```
## NOK:

```
x.on( 'change:item', item => {
    // do sth
    // do sth
    // do sth
} );

x.reduce( ( item, map ) => { map.set( item.name, item ); } );
```
## Rules

In other words:
- If your arrow function takes more than one line, always use curly brackets around the body and round bracket around the args list.
- Do not use curly brackets around the body if your arrow function takes only one line.

Reasoning – readability.

**Comment by pjasiun** [comment]
Maybe we should use this:
```
x.on( 'change:item', item => {
    // do sth
    // do sth
    // do sth
} );
```

Then the rule will be simpler:
 - one argument - no round brackets,
 - one line - no curly braces.

**Comment by Reinmar** [comment]
But such functions are still invisible for me and I noticed that not only me tend to add the brackets in such cases. In a blob of code `=>` dies (it is similar to equality operators) and `() =>` is more distinguishable.

**Comment by Reinmar** [comment]
We'll clarify this when switching to ESLint (ckeditor/ckeditor5#366).
