### ISSUE TITLE
Enumeration style

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#93]
We used to use numbers for enumeration: 

https://github.com/ckeditor/ckeditor5-core/blob/master/src/treemodel/position.js#L9-L12

This is the way we used to create enums. They are fast. They are simple. They do not use much memory. You will know when you will make a typo. That is true. In C++.

In JavaScript strings are not stored directly in memory, but in a map, so: using 'same' strings does not use more memory then creating `SAME` variable and assigning number to it. Compering strings also is not slower then number, even long strings. If you do not trust me check this out: 

http://jsperf.com/ck-compare-equal
http://jsperf.com/compare-different

But what is the problem with number as enum?

Well. There are few.

### Debugging.

In the console I see `1` instead of `same`, what is not very useful.

### Dependencies.

In JS I do not need to require `Foo` to call `bar.foo.method`, as long as `foo` method which use enumeration. Then, to call `bar.foo.method( Foo.VALUE );`, I need to require `Foo`. It creates a lot of dependencies, at this point, a lot of circular dependencies. And even if circular dependencies will not be a problem anymore, when we will start using ES6 modules, having more dependencies then we need will be still a bad smell.

### Long code.

`position1.compareWith( position2 ) == Position.BEFORE`

is simple longer then 

`position1.compareWith( position2 ) == 'before'`

is simple longer without any good reasons.

### Encapsulation.

This a an issue I met recently. What should I do if:

`Bom.method( type )`

calls:

`Foo.method( type );`

passing the type parameter which is enum (defined on `Foo`)?

`Bom.method( Foo.VALUE1 )` looks bad.

Coping these value looks like the way I should go, so I will have 

```
Bom.VALUE1 = Foo.VALUE1;
Bom.VALUE2 = Foo.VALUE2;
```

Then when I introduce VALUE3 I need to add `VALUE3 = 3` at the begging of the `foo.js`, then `Foo.VALUE3 = VALUE3` at the end and `Bom.VALUE3 = Foo.VALUE3` in `bom.js`. 

(╯°□°）╯︵ ┻━┻

### So...

Since we use ES6, I though: lets use Symbols. But they solve only the first issue.

So I do no see any good reason not to use strings as enumerable values, without special declarations. 

### Docs

Another question is how they should be documented. I think we could create a special namespace/type for each enum and put all values there, so all methods which use this enum as a value of the parameter, use this type instead of listing all possible values. In wold be useful to maintain documentation in the future, so if possible values will change we will not need to change all methods which use this enum.

**Comment by Reinmar** [comment]
Hm... I've never thought about this, but indeed it's irritating. Typos, meaningless values, requiring some modules just for the values of these enums, etc.

Using strings seems to be a reasonable solution. I can't name a single advantage of the current solution and can't name a single problem with strings other than "it just doesn't look ok" (when you have statically typed bg).

**Comment by scofalik** [comment]
Could we at least agree to use uppercase strings, so it looks like a constant value? I know, I know, it does not change anything, but `foo( bar, 'before' )` looks like it uses any generic string and operates on it, while `foo( bar, ns.BEFORE )` explicitly states what we use a flag to change `foo` behavior. `foo( bar, 'BEFORE' )` resembles a bit current solution.

I mean I agree with proposed solution, but I am an oldfag, I still prefer having those constants defined and looking like flags :P

**Comment by Reinmar** [comment]
+1 for upper case strings.

**Comment by pjasiun** [comment]
+1 for upper case. This is in fact what I already do, and it does not look bad: https://github.com/ckeditor/ckeditor5-core/blob/t/112-c/src/treeview/renderer.js#L23-L31

**Comment by scofalik** [comment]
What about documentating what a function returns if it used to return a flag? Example:

```javascript
/**
	 * Checks whether this position is before or after given position.
	 *
	 * @param {treeModel.Position} otherPosition Position to compare with.
	 * @returns {Number} A flag indicating whether this position is {@link #BEFORE} or
	 * {@link #AFTER} or {@link #SAME} as given position. If positions are in different roots,
	 * {@link #DIFFERENT} flag is returned.
	 */
	compareWith( otherPosition ) {
		// ...
	}
```

**Comment by Reinmar** [comment]
```
Now it returns: `'foo'` or `'bar'`.
```

**Comment by pjasiun** [comment]
We can define a special type for it:
```
/**
 * @class PositionRelation
 * ...
 */
```
All types may extend this class if there is no better mechanism in jsDoc.

Then set this as a type:
```
/**
 * @returns {PositionRelation}
 */
```
This way wen we add another type we won't need to update it in all methods which use this type.

**Comment by scofalik** [comment]
Okay, but can you provide a more insightful example? In code, not only JSDoc. After all `PositionRelation` is just a `string`.

**Comment by Reinmar** [comment]
Good point. Updating the set of values would be a problem, so we need a type for the return value.

**Comment by pjasiun** [comment]
There will be no code, only JSDoc.

And we could use `@typedef` for it: http://usejsdoc.org/tags-typedef.html

**Comment by scofalik** [comment]
Updated https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style#enumerables
