### ISSUE TITLE
Acronyms in names

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#94]
Should it be:
```
DOMElement
getDOMElement
```
Or:
```
domElement
getDomElement
```

I prefer the second one. With the only exception of "CK".

**Comment by pjasiun** [comment]
We could also have a rule that 2 letters shourtcuts are always upper case, so: `getUIElement`, but I prefer simpler rule and `getUiElement`.

So for me: `dom`, `ui`, but `CK` (as an exception).

**Comment by scofalik** [comment]
I am for *"we use camel-case also for shortcuts"*

**Comment by fredck** [comment]
Small detail... if we'll ever write this somewhere, let's call them "acronyms" or "abbreviations" (or both), not "shortcuts" ;)

I'm for following the general rule in this case, without special treatment. The only special case may be `CK` or `ck`, depending on the case.

Although this may sound strange in cases like `W3c` or `Ibm`. Maybe the "exception" that is valid for CK may be extended to all "all-cased" **names**.

**Comment by scofalik** [comment]
Yeah, `W3C` may look weird, but I doubt we will use such acronym :). We may use upper case for name acronyms. Let Piotr decide.

**Comment by pjasiun** [comment]
Right acronyms. In my opinion size of the letters in the code have more important meaning: 

`Foo` - is a class,
`FOO` - is a constant,
`foo` - is a variable.

I think we should use regular rules for all names. Otherwise it will be hard to tell if `W3CInfo` is a class or a variable, and how I should call them if I want to have both?

**Comment by fredck** [comment]
I mean `w3c` and `ibm` is also fine... I would propose same case for all-cased names.

**Comment by scofalik** [comment]
+1

**Comment by fredck** [comment]
> Otherwise it will be hard to tell if W3CInfo is a class or a variable, and how I should call them if I want to have both?

`W3CInfo` is a class... `w3cInfo` is a variable.

**Comment by pjasiun** [comment]
Then that is fine form me.

**Comment by Reinmar** [comment]
I think we could have special treatment for "invented names" (not sure whether this is the right term – but basically I mean company names, product names, etc). E.g. we wouldn't like to have `CkeditorError` :D Instead, we write `CKEditorError`. I'm fine with `IBMError` and similar as well. Acronyms would follow the "2+ letters" rule.

PS. Of course when talking about the first fragment of a camelCased token we would have `ckeditorError` and `ibmError`.

**Comment by scofalik** [comment]
I think this is a conclusion that we all can agree on:

"Acronyms are naturally written in uppercase, which stands against code style rules. When used in names in code, one should follow the default naming conventions. So class names should start uppercase and variable names should start lowercase. The rest of the name should be reasonable but it's up to coder. Example:
```javascript
class W3CError extends CKEditorError {
// ...
}
let w3cError = new W3CError();
```

**Comment by pjasiun** [comment]
With @Reinmar and @scofalik we decided that:

1) If it is the begging of the variable, it starts from the lower case and the whole word is lower case:
```
domError
uiError
ckeditorError
githubError
```

2) If it is the middle of the variable or it is the name of the class it starts for the upper case.
2.a) If it is the acronyms only the first letter is upper case (`Dom`, `Ui`).
2.b) If it is invented name we can use cases the way they were defined for the name (`CKEditor`, `GitHub`):
```
getDomError
getUiError
getCKEditorError
getGitHubError
```
And:
```
const domError = new DomError();
uiError = new UiError();
ckeditorError = new CKEditorError();
githubError = new GitHubError();
```

**Comment by pjasiun** [comment]
And we can assume that `W3C` is an invented name, in fact it is not an acronym, so one can use: `getW3CError` if one day we will find it useful.

**Comment by scofalik** [comment]
Added to wiki https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines#acronyms-and-proper-names

**Comment by Reinmar** [comment]
We talked today about adding the rule that two-letter acronyms and proper names should all be uppercase. So, e.g. `getUI` not `getUi`. No real reasons behind this other than "because Ui looks bad" :D.

I updated the documentation accordingly.

**Comment by pjasiun** [comment]
But Ai is fine, isn't is?
![image](https://cloud.githubusercontent.com/assets/1166967/12850429/efd12c62-cc24-11e5-8143-f9c83f16f9b4.png)

**Comment by Reinmar** [comment]
Don't know if trolling or not :P

**Comment by Reinmar** [comment]
If the intelligence is low then it can be `Ai`.
